version: '1.0.{build}'
install:
  - dotnet restore
platform:
  - x86
  - Any CPU
build_script:
  - dotnet build
test_script:
  - ps: ForEach ($proj in (Get-ChildItem -Path test -Recurse -Filter '*.csproj')) { dotnet test $proj.FullName }